name: Release Binary

on:
  push:
    branches:
      - main
    paths:
      - nerdfonts_installer.sh  # This ensures the workflow runs only if this file is changed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y shc

    - name: Install GitHub CLI
      run: |
        sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${GITHUB_TOKEN}" | gh auth login --with-token

    - name: Build binary
      run: |
        shc -f nerdfonts_installer.sh -o release/nerdfonts-installer
        chmod +x release/nerdfonts-installer

    - name: Create tarball
      run: |
        version=$(date +'%Y.%m.%d')".$(git rev-list --count HEAD)"
        tar -czf "release/nerdfonts-installer-${version}.tar.gz" -C release nerdfonts-installer
        echo "Version: ${version}" > release/version.txt

    - name: Create release
      id: create_release
      run: |
        version=$(date +'%Y.%m.%d')".$(git rev-list --count HEAD)"
        changelog=$(git log --oneline --pretty=format:"* %s (%h)" | head -n 20)
        echo "Changelog: $changelog" > release/changelog.txt
        
        gh release create "v${version}" release/nerdfonts-installer release/nerdfonts-installer-${version}.tar.gz release/changelog.txt --title "Release v${version}" --notes "$changelog"

    - name: Clean up old binaries
      run: |
        rm release/nerdfonts-installer
